networks:
  mynetwork:
    name: ${PROJECT:-docker}
    driver: bridge

services:
  nodejs:
    build:
      context: ./nodejs
    container_name: ${PROJECT:-docker}-node
    networks:
      - mynetwork
    volumes:
      - ./src:/app
      - domains:/domains-list
    working_dir: /app

  nginx:
    build:
      context: ./nginx
      args:
        worktrees: ${WORKTREES}
        app_domain: ${APP_DOMAIN}
    container_name: ${PROJECT:-docker}-nginx
    networks:
      - mynetwork
    ports:
      - "443:443"
    volumes:
      - domains:/domains-list
    depends_on:
      - nodejs

volumes:
  domains:
